[api]
availability_server_url = "https://dev.v1.mining-gateway.intmax.xyz/v1/availability"
withdrawal_gnark_prover_url = "https://dev.v1.mining-gateway.intmax.xyz/v1/gnark-withdraw-circuit"
claim_gnark_prover_url = "https://dev.v1.mining-gateway.intmax.xyz/v1/gnark-claim-circuit"
withdrawal_server_url="https://dev.v1.mining-gateway.intmax.xyz/v1/withdrawal/submit-proof"
tree_data_repository="InternetMaximalism/intmax2-mining"
gnark_get_proof_cooldown_in_sec = 15

[blockchain]
chain_id = 11155111
int1_address = "0x614b59031652d8BE8854AC012821DB40e55B7abB"
minter_address = "0x7EddE67D917B09DbB0E06a69551Af2C5ae97Bf8C"
token_address = "0x197d604281Ab7157d8a665b5aAD7435c652fE371"
single_deposit_gas_fee = "2000000000000000"
single_claim_gas_fee = "2000000000000000"

[service]
main_loop_cooldown_in_sec = 30
mining_max_cooldown_in_sec = 20
claim_max_cooldown_in_sec = 20
