[api]
availability_server_url = "https://dev.v1.mining-gateway.intmax.xyz/v1/availability"
withdrawal_gnark_prover_url = "https://dev.v1.mining-gateway.intmax.xyz/v1/gnark-withdraw-circuit"
claim_gnark_prover_url = "https://dev.v1.mining-gateway.intmax.xyz/v1/gnark-claim-circuit"
withdrawal_server_url="https://dev.v1.mining-gateway.intmax.xyz/v1/withdrawal/submit-proof"
tree_data_repository="kbizikav/sample-data-repo"
gnark_get_proof_cooldown_in_sec = 15

[blockchain]
chain_id = 31337
int1_address = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
minter_address = "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853"
token_address = "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707"
single_deposit_gas = 88000
single_claim_gas = 500000 

[service]
mining_max_cooldown_in_sec = 20
loop_cooldown_in_sec = 10