[api]
availability_server_url = "https://dev.v1.mining-gateway.intmax.xyz/v1/availability"
withdrawal_gnark_prover_url = "https://dev.v1.mining-gateway.intmax.xyz/v1/gnark-withdraw-circuit"
claim_gnark_prover_url = "https://dev.v1.mining-gateway.intmax.xyz/v1/gnark-claim-circuit"
withdrawal_server_url="https://dev.v1.mining-gateway.intmax.xyz/v1/withdrawal/submit-proof"
circulation_server_url="https://dev.v1.mining-gateway.intmax.xyz/v1/mining"
tree_data_repository="InternetMaximalism/intmax2-v1-mining-mock"
tree_data_directory="data"
tree_data_branch="main"
gnark_get_proof_cooldown_in_sec = 15

[blockchain]
chain_id = 11155111
int1_address = "0xF50C18ecd79475138b1f3AD786cA56Dd47122CD2"
minter_address = "0x3Bdb9CA4598bFc241479ae8C6f6F4056f3Ea8c4a"
token_address = "0x35C810028a7347C27635A18B57A840AEB44fbe86"
single_deposit_gas = 88000
single_claim_gas = 600000

[service]
repository_url = "https://github.com/InternetMaximalism/intmax2-mining-cli"
mining_max_cooldown_in_sec = 20
loop_cooldown_in_sec = 10
high_gas_retry_inverval_in_sec = 10

[env]
default_max_gas_price ="200"
default_mining_times="10"
default_mining_unit="0.1"