
[target.x86_64-apple-darwin]

[target.aarch64-apple-darwin]

#[target.x86_64-unknown-linux-gnu]
#linker = "x86_64-linux-musl-gcc"
#rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"